import com.jcaboclo.drools.example.model.LoanApplicant;
global com.jcaboclo.drools.example.model.LoanRate loanRate;

dialect "mvel"

rule "Checking Existing Debt Against Loan Amount"
 when
  LoanApplicant(loanAmount > (2 * existingDebt))
 then
  loanRate.setLoanStatus("Rejected - Too Much Debt");
  loanRate.setLoanRate(999);
end

rule "Checking Annual Salary is greater than 50000"
 when
  LoanApplicant(annualSalary <= 50000)
 then
  loanRate.setLoanStatus("Rejected - Too low salary");
  loanRate.setLoanRate(999);
end

rule "Checking Credit Score less than 550"
 when
  LoanApplicant(creditScore < 550 , annualSalary > 50000,  loanAmount < (2 * existingDebt))
 then
  loanRate.setLoanStatus("Rejected");
  loanRate.setLoanRate(999);
end

rule "Checking Credit Score less than 650"
 when
  LoanApplicant((creditScore < 650 && creditScore >= 550), annualSalary > 50000,  loanAmount < (2 * existingDebt))
 then
  loanRate.setLoanStatus("Approved");
  loanRate.setLoanRate(7.25);
end

rule "Checking Credit Score less than 750"
 when
  LoanApplicant((creditScore < 750 && creditScore >= 650), annualSalary > 50000,  loanAmount < (2 * existingDebt))
 then
  loanRate.setLoanStatus("Approved");
  loanRate.setLoanRate(6.25);
end

rule "Checking Credit Score greater than 750"
 when
  LoanApplicant(creditScore >= 750, annualSalary > 50000,  loanAmount < (2 * existingDebt))
 then
  loanRate.setLoanStatus("Approved");
  loanRate.setLoanRate(5.25);
end